name: haps

on:
  pull_request:
  push:
    branches:
      - "!gh-pages"
      - "**"
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  ubuntu-2004:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-latest]

    steps:
    - name: Check shellcheck version
      run: |
        shellcheck -V
        lsb_release -a

  ubuntu-1804:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-latest]

    steps:
    - name: Check shellcheck version
      run: |
        shellcheck -V
        lsb_release -a

  ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-latest]

    steps:
    - name: Check shellcheck version
      run: |
        shellcheck -V
        lsb_release -a