name: haps

on:
  pull_request:
  push:
    branches:
      - "!gh-pages"
      - "**"
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - name: Grab source
      uses: actions/checkout@v2

    - name: Run bash script
      run: |
        ls -la
        pwd
        ls -la ../
        make testscript